// export const baseUrl = 'http://10.0.2.2:3000/'
export const baseUrl = 'http://cacmarket.com/'
export const imageUrl = 'http://cacmarket.com/images/'
// export const baseUrl = 'http://6e9154c47ee9.ngrok.io/'
// export const api = 'https://talhats1999.000webhostapp.com/backend/backend/index.js'